# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kategoriview.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(440, 402)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 121, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelid = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelid.setObjectName("labelid")
        self.verticalLayout.addWidget(self.labelid)
        self.labelname = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelname.setObjectName("labelname")
        self.verticalLayout.addWidget(self.labelname)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(150, 10, 271, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.lineEditName = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditName.setObjectName("lineEditName")
        self.verticalLayout_2.addWidget(self.lineEditName)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 90, 411, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.insertButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.insertButton.setObjectName("insertButton")
        self.horizontalLayout_2.addWidget(self.insertButton)
        self.updateButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout_2.addWidget(self.updateButton)
        self.deleteButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout_2.addWidget(self.deleteButton)
        self.loadButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_2.addWidget(self.loadButton)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 140, 151, 16))
        self.label.setObjectName("label")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 160, 411, 101))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 290, 411, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.searchButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout_3.addWidget(self.searchButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.insertButton.clicked.connect(self.insertkategori)
        self.loadButton.clicked.connect(self.loadkategori)
        self.updateButton.clicked.connect(self.updatekategori)
        self.deleteButton.clicked.connect(self.deletekategori)
        self.tableWidget.cellClicked.connect(self.getById)
        self.searchButton.clicked.connect(self.searchkategori)
        
    def insertkategori(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="db_penjualan"
            )

            cursor = mydb.cursor()
            idkat = self.lineEdit.text()
            namekat = self.lineEditName.text()

            sql = "INSERT INTO kategori (id, name) VALUES (%s, %s)"
            val = (idkat, namekat)
            cursor.execute(sql, val)
            mydb.commit()
            self.label.setText("Data Kategori Berhasil Disimpan")
            self.lineEdit.clear()
            self.lineEditName.clear()

        except mc.Error as e:
            self.label.setText("Data Kategori Gagal Disimpan")
            
    def loadkategori(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="db_penjualan"
            )

            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM kategori ORDER BY id ASC")
            result = mycursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))
            self.label.setText("Data Kategori Berhasil Ditampilkan")
        except mc.Error as e:
            self.label.setText("Data Kategori Gagal DiLoad")
            
    def updatekategori(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="db_penjualan"
            )

            cursor = mydb.cursor()
            idkat = self.lineEdit.text()
            namekat = self.lineEditName.text()

            sql = "UPDATE kategori SET name = %s WHERE id = %s"
            val = (namekat, idkat)
            cursor.execute(sql, val)
            mydb.commit()
            self.label.setText("Data Kategori Berhasil Diupdate")
            self.lineEdit.clear()
            self.lineEditName.clear()
        except mc.Error as e:
            self.label.setText("Data Kategori Gagal Diupdate")

    def deletekategori(self):
        try:
            mydb = mc.connect(
                 host="localhost",
                user="root",
                password="",
                database="db_penjualan"
            )

            cursor = mydb.cursor()
            idkat = self.lineEdit.text()

            sql = "DELETE FROM kategori WHERE id = %s"
            val = (idkat,)
            cursor.execute(sql, val)
            mydb.commit()
            self.label.setText("Data Kategori Berhasil Dihapus")
            self.lineEdit.clear()
            self.lineEditName.clear()
        except mc.Error as e:
            self.label.setText("Data Kategori Gagal Dihapus")

    def getById(self, row, column):
        idkat = self.tableWidget.item(row, 0).text()
        namekat = self.tableWidget.item(row, 1).text()
        self.lineEdit.setText(idkat)
        self.lineEditName.setText(namekat)
        
    def searchkategori(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="db_penjualan"
            )

            mycursor = mydb.cursor()
            search_value = self.lineEdit_2.text()

            sql = "SELECT * FROM kategori WHERE id LIKE %s OR name LIKE %s ORDER BY ID ASC"
            cursor.execute(sql, (f"%{search_value}%", f"%{search_value}%"))
            result = cursor.fetchall()

            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))
            self.label.setText("Data Kategori Berhasil Dicari")
        except mc.Error as e:
            self.label.setText("Data Kategori Gagal Dicari")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Kategori"))
        self.labelid.setText(_translate("Form", "ID Kategori"))
        self.labelname.setText(_translate("Form", "Nama Kategori"))
        self.insertButton.setText(_translate("Form", "INSERT"))
        self.updateButton.setText(_translate("Form", "UPDATE"))
        self.deleteButton.setText(_translate("Form", "DELETE"))
        self.loadButton.setText(_translate("Form", "LOAD DATA"))
        self.label.setText(_translate("Form", "Data Kategori Berhasil Disimpan"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "No"))  
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nama Kategori"))
        self.searchButton.setText(_translate("Form", "Search"))
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
